# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "tests/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            sudo apt update
            sudo apt install --upgrade cmake>=3.13 make
            python3 -m venv venv
            . venv/bin/activate 
            pip install -r tests/requirements.txt
    
      - run:
          name: build executable
          command: |
            mkdir build 
            cd build && cmake .. && make
            
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest ./tests -v


      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
